### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by joepie91** [zhm/pg-query-parser#1]
This repository seems to contain the documentation for `pg-query-native` rather than `pg-query-parser` - eg. `deparse` isn't documented. Is this intended?

**Comment by zhm** [comment]
Yes, you're correct. Sorry about that, I just haven't had time to get it documented. There are 3 scripts in the root of the repo which demonstrate the top-level API that I was using for verification.

https://github.com/zhm/pg-query-parser/blob/master/deparse
https://github.com/zhm/pg-query-parser/blob/master/parse
https://github.com/zhm/pg-query-parser/blob/master/verify

`verify` runs a complete parse + deparse + parse and verifies the symmetry of the parsing/deparsing.

**Comment by zhm** [comment]
Thanks for reporting this, the README is being updated on the v1 branch.

https://github.com/zhm/pg-query-parser/blob/v1/README.md
